Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xa1fe4db0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xa81bcc50>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xa44a8c10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xa2e311f0>
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa4045890>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa7e46c90>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.































Setting up...
-----------------------------------
Cogs:
-----------------------------------
cogs.helpcommand.py, cogs.JesterInfo.py, cogs.Chatbot.py, cogs.Feedback.py, cogs.music.py, cogs.Countries.py, cogs.Staff.py, cogs.Snipe.py, cogs.Fun.py, cogs.DiscordTogether.py, cogs.Moderation.py, cogs.Games.py, cogs.Utils.py, cogs.Images.py, cogs.Economy.py, cogs.Misc.py, cogs.Levels.py, cogs.Config.py, cogs.Love.py, cogs.event.py, cogs.Gifs.py, cogs.Crypto.py
Loaded Cogs Successfully! Total Cogs: 22
-----------------------------------
Running the bot...
-----------------------------------
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from core.Bot import JesterBot
  File "/home/pi/Desktop/JesterBot/core/Bot.py", line 12, in <module>
    from core.main.check import run_channel_send
  File "/home/pi/Desktop/JesterBot/core/main/check.py", line 5, in <module>
    from core.utils.comedy import fact, quote, joke, pickup
  File "/home/pi/Desktop/JesterBot/core/utils/comedy.py", line 1, in <module>
    import vacefron, randfacts, asyncpraw, datetime, json, requests
  File "/home/pi/.local/lib/python3.7/site-packages/asyncpraw/__init__.py", line 14, in <module>
    from .reddit import Reddit  # NOQA
  File "/home/pi/.local/lib/python3.7/site-packages/asyncpraw/reddit.py", line 47, in <module>
    from update_checker import update_check
  File "/home/pi/.local/lib/python3.7/site-packages/update_checker.py", line 5, in <module>
    import requests
  File "/home/pi/.local/lib/python3.7/site-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/home/pi/.local/lib/python3.7/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/pi/.local/lib/python3.7/site-packages/charset_normalizer/api.py", line 9, in <module>
    from charset_normalizer.constant import TOO_SMALL_SEQUENCE, TOO_BIG_SEQUENCE, IANA_SUPPORTED
  File "/home/pi/.local/lib/python3.7/site-packages/charset_normalizer/constant.py", line 55, in <module>
    IGNORECASE
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 816, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 529, in _parse
    this = sourceget()
  File "/usr/lib/python3.7/sre_parse.py", line 256, in get
    self.__next()
  File "/usr/lib/python3.7/sre_parse.py", line 248, in __next
    self.next = char
KeyboardInterrupt
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa7ebcff0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa7e64f90>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa41b53b0>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa7ebaf70>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa7e66ff0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa36ab210>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa62d62b0>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa27cb0b0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xa74df250>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)































Setting up...
-----------------------------------
Cogs:
-----------------------------------
cogs.helpcommand.py, cogs.JesterInfo.py, cogs.Chatbot.py, cogs.Feedback.py, cogs.music.py, cogs.Countries.py, cogs.Staff.py, cogs.Snipe.py, cogs.Fun.py, cogs.DiscordTogether.py, cogs.Moderation.py, cogs.Games.py, cogs.Utils.py, cogs.Images.py, cogs.Economy.py, cogs.Misc.py, cogs.Levels.py, cogs.Config.py, cogs.Love.py, cogs.event.py, cogs.Gifs.py, cogs.Crypto.py
Loaded Cogs Successfully! Total Cogs: 22
-----------------------------------
Running the bot...
-----------------------------------
Connected to bot. Latency: 127 ms
Client Ready!
Guilds:
-----------------------------------
[593805403016396817, 801958621104832542, 764648063032885288, 827088097799831603, 843107189165260830, 851164219817984020, 846032738707832882, 110373943822540800, 817371635233062913, 782966978918744105, 800102903507058688, 834413080573378610, 861310040292065331, 673303075280388117, 793102507156701184, 831109278382948362, 859435997040345108, 707335479326015559, 850425394192580628, 809623148513329162, 808781108095352832, 813837741770801163, 808057945957990420, 823751270414286908, 837790134790783006, 772083939112124417, 817728197016944681, 840995227534622782, 834509878205874197, 830161446523371540, 704287808252280882, 809747740115992607, 868155750697021501, 861253572787175456, 824399343917989930, 853274948231102484, 671687376745005066, 781547697667964928, 833677482589683754, 834073210063552553, 812942306764259399, 868802716607078431, 799321945518505984, 849184957414899733, 829959100171026453, 804393586241437726, 803430815714902057, 812053139350880287, 869732483564982302, 772497051132493874, 831775556084170782, 826494680002723870, 854816114509217812, 814545701479645264, 801255165202006036, 684235302650511411, 830502079377178684]
Admins:
-----------------------------------
Fred123#7205
stealthninja#1990
Client Disconnected.
Version 7.3.1 of asyncpraw is outdated. Version 7.4.0 was released Friday July 30, 2021.
